### ISSUE TITLE
Try other graphics frameworks for visualization

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/Quac.jl#21]
If we could use Makie for visualization, then we could delay loading Makie and speed up TTFT (_Time To First Task_) just like `Tenet` and `OptimizedEinsum`.

Related to #11

**Comment by jofrevalles** [comment]
Wouldn't it be the same if we are using `@require` for `Luxor`?

**Comment by mofeing** [comment]
Yes and no. Users usually import `Makie` or a backend, so this part of the code is automatically loaded. But users don't usually load `Luxor` so it concur in some cognitive load to make them import `Luxor` to make plots work.

Also, it's just SVG code so it easily be created but I don't know why `Luxor` is so heavy.
